import type { Metadata } from 'next'
// 文档 https://mui.com/material-ui/integrations/nextjs/
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'

import { ThemeProvider } from '@mui/material/styles'
import theme from './theme'

import './global.scss'

export const metadata: Metadata = {
  title: 'Edge Runners',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
