import { Orbitron } from 'next/font/google'
// 文档 https://mui.com/material-ui/integrations/nextjs/
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'

import { ThemeProvider } from '@mui/material/styles'
import theme from './theme'
import App from './app'

import './global.scss'

// 引入 Orbitron 字体
const orbitron = Orbitron({
  subsets: ['latin'],
  weight: ['400', '700'], // 根据需要选择字体粗细
})

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={orbitron.className}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Edge Runners</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <App>{children}</App>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
